EmployeeAttendanceManagement/EmployeeAttendanceManagement/urls.py
from django.contrib import admin
from django.urls import path,include
from testapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index.as_view()),
    path('contactus/',views.contactus.as_view(),name='contactus'),
    path('about/',views.about.as_view()),
    path('dashboard/',views.dashboard.as_view()),
    path('accounts/',include('django.contrib.auth.urls')),
    path('addemployee/',views.addemployee),
    path('detailsemployee/',views.detailsemployee),
    path('deleteemployee/<int:eid>',views.deleteemployee),
    path('updateemployee/<int:eid>',views.updateemployee),
    path('addattendance/',views.addattendance),
    path('detailsattendance/',views.detailsattendance,name='detailsattendance'),
    path('deleteattendance/<int:id>',views.deleteattendance),
    path('updateattendance/<int:pk>',views.updateattendance.as_view()),
    path('passwordchange/',views.passwordchange)
]

EmployeeAttendanceManagement/testapp/models.py
from django.db import models
from django.urls import reverse

GENDER_CHOICES=(
    ('Male','Male'),
    ('Female','Female')
)

# Create your models here.
class Contact(models.Model):
    name=models.CharField(max_length=30)
    email=models.EmailField()
    contactno=models.CharField(max_length=10)
    message=models.TextField()

    def get_absolute_url(self):
        return reverse('contactus')

class Employee(models.Model):
    eid=models.IntegerField(primary_key=True)
    first_name=models.CharField(max_length=30)
    last_name=models.CharField(max_length=20)
    salary=models.IntegerField()
    gender=models.CharField(max_length=6,choices=GENDER_CHOICES,default=1)
    contactno=models.CharField(max_length=10)
    email=models.CharField(max_length=30)
    country=models.CharField(max_length=30)
    city=models.CharField(max_length=20)
    pincode=models.IntegerField()
    address=models.CharField(max_length=60)

    def __str__(self):
        return self.first_name+' '+self.last_name

class Attendance(models.Model):
    employee=models.ForeignKey(Employee,on_delete=models.CASCADE,default=1)
    attendancedate=models.DateField()
    in_time=models.TimeField()
    out_time=models.TimeField()
    description=models.TextField()

    def get_absolute_url(self):
        return reverse('detailsattendance')

EmployeeAttendanceManagement/testapp/forms.py
from django import forms
from testapp.models import Contact,Employee,Attendance

class ContactForm(forms.ModelForm):
    class Meta:
        model=Contact
        fields='__all__'

GENDER_CHOICES=(
    ('Male','Male'),
    ('Female','Female')
)

class EmployeeForm(forms.Form,forms.ModelForm):
    gender=forms.ChoiceField(choices=GENDER_CHOICES,widget=forms.RadioSelect(),initial='Male')
    class Meta:
        model=Employee
        fields=('eid','first_name','last_name','salary','gender','contactno','email','country','city','pincode','address')


class AttendanceForm(forms.ModelForm) :
    class Meta:
        model=Attendance
        fields='__all__'

class PasswordChangeForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField()

EmployeeAttendanceManagement/testapp/views.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView,CreateView,UpdateView
from testapp.models import Contact,Employee,Attendance
from testapp.forms import EmployeeForm,AttendanceForm,PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User

# Create your views here.
class Counter:
    count=1
    def increment(self):
        self.count=self.count+1
        return ' '

class index(TemplateView):
    template_name='testapp/index.html'

class contactus(CreateView):
    model=Contact
    template_name='testapp/contactus.html'
    fields=('name','email','contactno','message')

class about(TemplateView):
    template_name='testapp/about.html'

@method_decorator(login_required,name='dispatch')
class dashboard(TemplateView):
    template_name='testapp/dashboard.html'

@login_required
def addemployee(request):
    form=EmployeeForm()
    if request.method=='POST':
        form=EmployeeForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            eid_value=form.cleaned_data['eid']
            gender_value=form.cleaned_data['gender']
            employee=Employee.objects.get(eid=eid_value)
            employee.gender=gender_value
            employee.save()
            return redirect('detailsemployee/')

    return render(request,'testapp/addemployee.html',{'form':form})

@login_required
def detailsemployee(request):
    emp_list=Employee.objects.all()
    counter=Counter()
    return render(request,'testapp/detailsemployee.html',{'emp_list':emp_list,'counter':counter})

@login_required
def deleteemployee(request,eid):
    employee=Employee.objects.get(eid=eid)
    employee.delete()
    return redirect('/detailsemployee')

@login_required
def updateemployee(request,eid):
    employee=Employee.objects.get(eid=eid)
    if request.method=='POST':
        form=EmployeeForm(request.POST,instance=employee)
        if form.is_valid():
            form.save(commit=True)
            return redirect('/detailsemployee')

    return render(request,'testapp/updateemployee.html',{'employee':employee})

@login_required
def addattendance(request):
    form=AttendanceForm()
    emp_list=Employee.objects.all()
    if request.method=='POST':
        form=AttendanceForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect('/detailsattendance')

    return render(request,'testapp/addattendance.html',{'form':form,'emp_list':emp_list})

@login_required
def detailsattendance(request):
    attendance_list=Attendance.objects.all()
    counter=Counter()
    return render(request,'testapp/detailsattendance.html',{'attendance_list':attendance_list,'counter':counter})

@login_required
def deleteattendance(request,id):
    attendance=Attendance.objects.get(id=id)
    attendance.delete()
    return redirect('/detailsattendance')

@method_decorator(login_required,name='dispatch')
class updateattendance(UpdateView):
    model=Attendance
    fields=('employee','attendancedate','in_time','out_time','description')
    template_name='testapp/updateattendance.html'


def passwordchange(request):
    form=PasswordChangeForm()
    if request.method=='POST':
        form=PasswordChangeForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            try:
                    u=User.objects.get(username__exact=username)
                    u.set_password(password)
                    u.save()
                    return render(request,'testapp/passwordchange.html',{'form':PasswordChangeForm(),'message':'Password change successfully!','class':'alert alert-success'})
            except:
                return render(request,'testapp/passwordchange.html',{'form':PasswordChangeForm(),'message':'Username Does not exist !','class':'alert alert-success'})
    return render(request,'testapp/passwordchange.html',{'form':form})

EmployeeAttendanceManagement/templates/testapp/about.html
<!DOCTYPE html>
{% extends 'testapp/base.html' %}
{% load staticfiles %}
{% block main_block %}
  <link rel="stylesheet" href="{% static 'css/main1.css' %}">
{% endblock %}

{% block child_block %}
<div id="about">
      <div>
          <div class="container">
                  <h2>About Employee Attendance Management</h2>
          </div>
      </div>
      <div class="container">
              <div class="row">
                      <div class="col-8 text-justify mt-4">
                          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempore, explicabo nobis, dolor aut pariatur, facilis sit labore totam harum vel voluptatibus. Beatae sed explicabo repudiandae dolorem officia natus unde eaque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde voluptatem recusandae tempora accusamus necessitatibus facere quidem exercitationem doloribus in quis. Accusantium aperiam inventore maxime facere iure ratione, incidunt tenetur suscipit. Minima ipsa adipisci dignissimos necessitatibus perferendis fugiat totam aliquid expedita, cupiditate veritatis dolor magni ipsum quod nostrum nam ratione doloremque tempore quo cumque dolores? Placeat obcaecati praesentium ab sit alias iusto officia, dolorem nisi iste reprehenderit esse odio a. Consequuntur consequatur minima, quidem reprehenderit repellat explicabo facere labore provident debitis doloremque a ratione laboriosam? Non quae magni incidunt. Quibusdam, alias ullam ipsa reprehenderit iure voluptas odio ipsum a aspernatur eos.
                          </p>
                          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem repellat expedita doloremque similique adipisci harum sequi eligendi explicabo dolorem, saepe qui, odit ex quidem vitae dicta officiis voluptas culpa? Sunt reiciendis, sapiente porro est non, ullam eligendi tenetur, assumenda possimus culpa asperiores similique obcaecati rem pariatur. Fugiat ipsum quisquam facere.</p>
                      </div>
                  </div>
      </div>
  </div>
{% endblock %}

EmployeeAttendanceManagement/templates/testapp/addattendance.html
<!DOCTYPE html>
{% extends 'testapp/base.html' %}
{% load staticfiles %}
{% block main_block %}
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
  <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
{% endblock %}
{% block child_block %}
  <h3 style="background-color: #BE5869;padding: 7px 100px;" class="text-white">Add Attendance</h3>
  <div class="container">
    <div class="row">
        <div class="col-6 col-md-12 mx-auto mb-3">
          <form method="post">
              <label for="id_employee">Employee</label><br>
              <select name="employee" id="id_employee" style="padding: 6px 20px 6px 10px;">
                {% for employee in emp_list %}
                  <option value="{{employee.eid}}">{{employee.first_name}}{{' '}}{{employee.last_name}}</option>
                {% endfor %}
              </select><br><br>
              <label for="datepicker">Attendance Date</label>
              <input id="datepicker" width="210" name="attendancedate"><br>
              <label for="id_in_time">In_Time</label>
              <input id="id_in_time" width="210" name="in_time"><br>
              <label for="id_out_time">Out_Time</label>
              <input id="id_out_time" width="210" name="out_time"><br>
              <label for="">Description</label><br>
              <textarea name="description" rows="4" cols="34" style="resize:none;outline:none;" class="mb-3"></textarea><br>
              <input type="submit" name="" value="Add Attendance" style="border: none;background-color: #BE5869;color: white;padding: 5px 14px;">
              <a href="/dashboard" style="background-color: #a8783e;color:white;padding:6px 12px;margin-left: 5px;">Back</a>
              {% csrf_token %}
          </form>
        </div>
      </div>
    </div>

  <script>
        $('#datepicker').datepicker();
        $('#id_in_time').timepicker();
        $('#id_out_time').timepicker();
  </script>
{% endblock %}

EmployeeAttendanceManagement/templates/testapp/addemployee.html
<!DOCTYPE html>
{% extends 'testapp/base.html' %}
{% load staticfiles %}
{% block main_block %}
  <link rel="stylesheet" href="{% static 'css/dashboardstyle.css' %}">
{% endblock %}

{% block child_block %}
      <h3 style="background-color: #BE5869;padding: 7px 100px;" class="text-white">Add Employee</h3>
      <div class="container-fluid">
        <div class="row">
            <div class="col-10 col-md-3  ml-md-5 mx-auto">
              <form method="post" class="d-block">
                  <input type="text" name="eid" value="" placeholder="Id" id="id_eid"><br>
                  <input type="text" name="first_name" value="" placeholder="First Name" id="id_first_name"><br>
                  <input type="text" name="last_name" value="" placeholder="Last Name" id="id_last_name"><br>
                  <input type="text" name="salary" value="" placeholder="Salary" id="id_salary"><br>
                  <input type="radio" name="gender" value="Male" checked id="id_gender_0" class="my-2">
                  Male
                  <input type="radio" name="gender" value="Female" id="id_gender_1" class="ml-4 my-2">
                  Female <br>
                  <input type="text" name="contactno" value="" placeholder="Contact No" id="id_contactno"><br>
                  <input type="text" name="email" value="" placeholder="Email" id="id_email"><br>
                  <input type="text" name="country" value="" placeholder="Country" id="id_country"><br>
                  <input type="text" name="city" value="" placeholder="City" id="id_city"><br>
                  <input type="text" name="pincode" value="" placeholder="Pincode" id="id_pincode"><br>
                  <input type="text" name="address" value="" placeholder="Address" id="id_address"><br>
                  <input type="submit" name="" value="Submit">
                  <a href="/dashboard" style="background-color: #a8783e;color:white;padding:6px 12px;margin-left: 5px;">Back</a>
                  {% csrf_token %}

                </form>
              </div>
          </div>
      </div>

{% endblock %}

EmployeeAttendanceManagement/templates/testapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/base_main.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab&display=swap" rel="stylesheet">
    {% block main_block %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/loading.css' %}">
    <script src="{% static 'js/loading.js' %}" charset="utf-8" id="first"></script>
</head>
<body>
  <div id="load" style="background: url('{% static 'images/Preloader_3.gif' %}') center no-repeat #fff"></div>
  <div id="contents">
      <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container-fluid">
                  <a href="/" class="navbar-brand"><h1><span>E</span>mployee <span>A</span>ttendance <span>M</span>anagement</h1></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto">
                  <i class="fa fa-home mt-2" style="color:#ccc;"></i>
                  <li class="nav-item mr-4"><a href="/" class="nav-link py-0">home</a></li>
                  {% if request.user.is_authenticated %}
                  <i class="fa fa-users mt-2" style="color:#ccc;"></i>
                  <li class="nav-item mr-4"><a href="#" class="nav-link py-0">Employee</a></li>
                  <i class="fa fa-clock-o mt-2" style="color:#ccc;"></i>
                  <li class="nav-item mr-4"><a href="#" class="nav-link py-0">Attendance</a></li>
                  <i class="fa fa-tachometer mt-2" style="color:#ccc;"></i>
                  <li class="nav-item mr-4"><a href="/dashboard" class="nav-link py-0">dashboard</a></li>
                  <i class="fa fa-sign-out mt-2" style="color:#ccc;"></i>
                  <li class="nav-item mr-4"><a href="/accounts/logout" class="nav-link py-0">logout</a></li>
                  {% else %}

                  <i class="fa fa-info-circle mt-2" style="color:#ccc;"></i>
                  <li class="nav-item mr-4"><a href="/about" class="nav-link py-0">about</a></li>
                  <i class="fa fa-address-book mt-2" style="color:#ccc;"></i>
                  <li class="nav-item mr-4"><a href="/contactus" class="nav-link py-0">contact us</a></li>
                  <i class="fa fa-sign-in mt-2" style="color:#ccc;"></i>
                  <li class="nav-item mr-4"><a href="/accounts/login" class="nav-link py-0">login</a></li>
                  {% endif %}
              </ul>
          </div>
          </div>
      </nav>

      {% block child_block%}
      {% endblock %}

      <footer>
          <p>Copyright &copy; 2019 All rights reserved</p>
      </footer>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

EmployeeAttendanceManagement/templates/testapp/contactus.html
<!DOCTYPE html>
{% extends 'testapp/base.html' %}
{% load staticfiles %}
{% block main_block %}
  <link rel="stylesheet" href="{% static 'css/main1.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block child_block %}
<div id="contact">
      <div>
          <div class="container">
                  <div class="row">
                          <div class="col-4 mx-auto">
                              <h3>CONTACT</h3>
                          </div>
                          <div class="col-4">
                              <h3>Contact Info</h3>
                          </div>
                  </div>
          </div>
      </div>
      <div class="container">
          <div class="row">
              <div class="col-md-4 mt-4 mx-auto col-10">
              <ul class="list-unstyled">
                  <li class="media">
                      <i class="fa fa-map-marker mr-3" aria-hidden="true"></i>
                          <div class="media-body">
                          <p>'2447 Sharp Street\nJuanfurt, DE 51168' <br>
                              '9299 Harper Summit\nWest Brandon, SD 12873'
                          </p>
                          </div>
                      </li>
                      <li class="media my-4">
                          <i class="fa fa-phone mr-3" aria-hidden="true"></i>
                          <div class="media-body">
                              <p>support:'001-950-643-9934x45016'</p>
                          </div>
                      </li>
                      <li class="media">
                              <i class="fa fa-envelope mr-3" aria-hidden="true"></i>
                          <div class="media-body">
                              <p>'moralesscott@yahoo.com' <br>
                              'danielkevin@reyes-carrillo.biz' <br>
                              'ewise@taylor-washington.biz'</p>
                          </div>
                      </li>
                  </ul>
              </div>
              <div class="col-md-4 mt-4 col-10 mx-auto">
                  <form onsubmit="return validation()" method="post">
                      <input type="text" placeholder="Name" name="name" id="name_field">
                      <span id="name_error" style="visibility: hidden;">Name cannot be empty</span><br>
                      <input type="text" placeholder="Email" name="email" id="email_field">
                      <span id="email_error" style="visibility: hidden;">Email should be in valid form</span>
                      <br>
                      <input type="text" placeholder="ContactNo" name="contactno" id="contactno_field">
                      <span id="contactno_error" style="visibility: hidden;">contactno should be contain 10 digits</span>
                      <br>
                      <textarea cols="30" rows="4" placeholder="Your Message" name="message" id="message_field"></textarea>
                      <span id="message_error" style="visibility: hidden;">This field cannot be empty</span>
                      <br>
                      <input type="submit" value="Send Message" id="submit">
                      {% csrf_token %}
                  </form>

              </div>
          </div>
      </div>
      </div>

      <script src="{% static 'js/action_1.js' %}" charset="utf-8"></script>
{% endblock %}

EmployeeAttendanceManagement/templates/testapp/dashboard.html
<!DOCTYPE html>
{% extends 'testapp/base.html' %}
{% load staticfiles %}
{% block main_block %}
    <style>
    ul#list li {
      background-color: #686963;
    }
        li#item:hover {
          background-color: #778472;
        }
    </style>
{% endblock %}
{% block child_block %}
  <h3 style="background-color: #BE5869;padding: 7px 100px;" class="text-white">Dashboard</h3>
  <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 col-10 mx-auto">
              <ul class="list-unstyled" id="list">
                <li id=item class="my-2 w-100"><a href="/addemployee" class="text-white text-center text-decoration-none d-block">Add Employee</a></li>
                <li id=item class="my-2 w-100"><a href="/detailsemployee" class="text-white text-center text-decoration-none d-block">Details Employee</a></li>
                <li id=item class="my-2 w-100"><a href="/addattendance" class="text-white text-center text-decoration-none d-block">Add Attendance</a></li>
                <li id=item class="my-2 w-100"><a href="/detailsattendance" class="text-white text-center text-decoration-none d-block">Details Attendance</a></li>
              </ul>
            </div>
        </div>
</div>
{% endblock %}

EmployeeAttendanceManagement/templates/testapp/detailsattendance.html
<!DOCTYPE html>
{% extends 'testapp/base.html' %}
{% load staticfiles %}
{% block main_block %}
  <link rel="stylesheet" href="{% static 'css/dashboardstyle.css' %}">
{% endblock %}
{% block child_block %}
    <h3 style="background-color: #BE5869;padding: 7px 100px;" class="text-white">Attendance List</h3>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
              {% if attendance_list %}
                <table>
                  <thead>
                    <th>S.No</th>
                    <th>Employee Name</th>
                    <th>Attendance Date</th>
                    <th>In_time</th>
                    <th>Out_time</th>
                    <th>Description</th>
                    <th>Actions</th>
                  </thead>
                  {% for attendance in attendance_list %}
                  <tr>
                    <td>{{counter.count}}</td>{{counter.increment}}
                    <td>{{attendance.employee}}</td>
                    <td>{{attendance.attendancedate}}</td>
                    <td>{{attendance.in_time}}</td>
                    <td>{{attendance.out_time}}</td>
                    <td>{{attendance.description}}</td>
                    <td><a href="/updateattendance/{{attendance.id}}">Update</a><a href="/deleteattendance/{{attendance.id}}" class="ml-2">Delete</a></td>
                  </tr>
                  {% endfor %}
                </table>
              {% else %}
                <p>No Attendance Available</p>
              {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

EmployeeAttendanceManagement/templates/testapp/detailsemployee.html
<!DOCTYPE html>
{% extends 'testapp/base.html' %}
{% load staticfiles %}
{% block main_block %}
  <link rel="stylesheet" href="{% static 'css/dashboardstyle.css' %}">
{% endblock %}
{% block child_block %}
    <h3 style="background-color: #BE5869;padding: 7px 100px;" class="text-white">Employees List</h3>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
              {% if emp_list %}
                <table>
                  <thead>
                    <th>S.No</th>
                    <th>Employee Name</th>
                    <th>Salary</th>
                    <th>Gender</th>
                    <th>Email</th>
                    <th>City</th>
                    <th>Country</th>
                    <th>Action</th>
                  </thead>
                  {% for employee in emp_list %}
                  <tr>
                    <td>{{counter.count}}</td>{{counter.increment}}
                    <td>{{employee.first_name}}{{' '}}{{employee.last_name}}</td>
                    <td>{{employee.salary}}</td>
                    <td>{{employee.gender}}</td>
                    <td>{{employee.email}}</td>
                    <td>{{employee.city}}</td>
                    <td>{{employee.country}}</td>
                    <td><a href="/updateemployee/{{employee.eid}}">Update</a><a href="/deleteemployee/{{employee.eid}}" class="ml-2">Delete</a></td>
                  </tr>
                  {% endfor %}
                </table>
              {% else %}
                <p>No Employee Available</p>
              {% endif %}
            </div>
        </div>
    </div>


{% endblock %}

EmployeeAttendanceManagement/templates/testapp/passwordchange.html
<!DOCTYPE html>
{% extends 'testapp/base.html' %}
{% load staticfiles %}
{% block main_block %}

{% endblock %}
{% block child_block %}
    <h3 style="background-color: #BE5869;padding: 7px 100px;" class="text-white">Password Change</h3>
    <div class="container">
      <div class="{{class}}" role="alert">
          {{message}}
      </div>
        <div class="row">
            <div class="col my-4">
              <form method="post">
                  {{form.as_p}}
                  <input type="submit" name="" value="Change Password" class="text-white p-1" style="background-color: #d16666;border:none;">
                  {% csrf_token %}
              </form>
            </div>
        </div>
    </div>
{% endblock %}

EmployeeAttendanceManagement/templates/testapp/updateattendance.html
<!DOCTYPE html>
{% extends 'testapp/base.html' %}
{% load staticfiles %}
{% block main_block %}
  <link rel="stylesheet" href="{% static 'css/dashboardstyle.css' %}">
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
  <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
{% endblock %}
{% block child_block %}
<h3 style="background-color: #BE5869;padding: 7px 100px;" class="text-white">Update Attendance</h3>
<div class="container-fluid">
  <div class="row">
      <div class="col-10 col-md-3  ml-md-5 mx-auto">
          <form method="post" class="d-block">
          {{form.as_p}}
          <input type="submit" name="" value="Update Attendance">
          <a href="/detailsattendance" style="background-color: #a8783e;color:white;padding:6px 12px;">Back</a>
              {% csrf_token %}
          </form>
        </div>
      </div>
    </div>


      <script>
            $('#datepicker').datepicker();
            $('#id_in_time').timepicker();
            $('#id_out_time').timepicker();
      </script>
{% endblock %}

EmployeeAttendanceManagement/templates/testapp/updateemployee.html
<!DOCTYPE html>
{% extends 'testapp/base.html' %}
{% load staticfiles %}
{% block main_block %}
  <link rel="stylesheet" href="{% static 'css/dashboardstyle.css' %}">
{% endblock %}
{% block child_block %}
    <h3 style="background-color: #BE5869;padding: 7px 100px;" class="text-white">Update Employee</h3>
    <div class="container-fluid">
      <div class="row">
          <div class="col-10 col-md-3  ml-md-5 mx-auto">
              <form method="post" class="d-block">
              <label for="id_eid">Eid:</label>
              <input type="text" name="eid" value="{{employee.eid}}" id="id_eid"><br>
              <label for="id_first_name">First Name:</label>
              <input type="text" name="first_name" value="{{employee.first_name}}" id="id_first_name"><br>
              <label for="">Last Name:</label>
              <input type="text" name="last_name" value="{{employee.last_name}}" id="id_last_name"><br>
              <label for="">Salary</label>
              <input type="text" name="salary" value="{{employee.salary}}" id="id_salary"><br>
              Gender:<br>
              {% if employee.gender == 'Male' %}
                <input type="radio" name="gender" value="Male" checked>
                Male
              {% else %}
                <input type="radio" name="gender" value="Male">
                Male
              {% endif %}
              {% if employee.gender == 'Female' %}
                <input type="radio" name="gender" value="Female" checked class="ml-2">
                Female
              {% else %}
                <input type="radio" name="gender" value="Female" class="ml-2">
                Female
              {% endif %}
              <br>
              <label for="id_contactno">Contact No:</label>
              <input type="text" name="contactno" value="{{employee.contactno}}" id="id_contactno"><br>
              <label for="id_email">Email:</label>
              <input type="text" name="email" value="{{employee.email}}" id="id_email"><br>
              <label for="id_city">City:</label>
              <input type="text" name="city" value="{{employee.city}}" id="id_city"><br>
              <label for="id_country">Country:</label>
              <input type="text" name="country" value="{{employee.country}}" id="id_country"><br>
              <label for="id_pincode">Pincode:</label>
              <input type="text" name="pincode" value="{{employee.pincode}}" id="id_pincode"><br>
              <label for="id_address">Address:</label>
              <input type="text" name="address" value="{{employee.address}}" id="id_address"><br>

              <input type="submit" name="" value="Update Record">
              <a href="/detailsemployee" style="background-color: #a8783e;color:white;padding:6px 12px;">Back</a>
                  {% csrf_token %}
              </form>
            </div>
          </div>
        </div>
{% endblock %}